version: '3.5'
services:
  laravel:
    build: .
    container_name: laravel
    hostname: laravel.localhost
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./site.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - HOSTNAME=laravel.localhost
    ports:
      - "80"
    labels:
      - "traefik.backend=laravel"
      - "traefik.frontend.rule=Host:laravel.docker.ianmonroe.com"
      - "traefik.port=80"
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=http,https"
    networks:
      - laravel_private
      - laravel_public

networks:
  laravel_public:
    external:
      name: frontend
  laravel_private:
    driver: bridge
