version: '3'
services:

  traefik:
    image: traefik:1.5.4
    restart: always
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./stack_admin/traefik/traefik.toml:/traefik.toml
      - ./stack_admin/traefik/acme.json:/acme.json
    container_name: traefik
    networks:
      - frontend
      - backend

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: --templates http://templates/templates.json
    labels:
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=PathPrefixStrip:/portainer"
      - "traefik.port=9000"
      - "traefik.enable=true"
      - "traefik.frontend.redirect.regex=^(.*)/portainer$$"
      - "traefik.frontend.redirect.replacement=$$1/portainer/"
      - "traefik.frontend.rule=PathPrefix:/portainer;ReplacePathRegex: ^/portainer/(.*) /$$1"
    #managed by Traefik
    #ports:
    #  - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./stack_admin/portainer/data:/data
      - ./shared_data:/shared
    environment:
      - TZ="America/Denver"
    networks:
      - frontend
      - backend

  watchtower:
    container_name: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: default

