version: '3.5'

services:

  wordpress:
    image: wordpress
    container_name: wordpress-webserver
    restart: always
    #ports:
    #  - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress/wp-content/themes:/var/www/html/wp-content/themes/
      - ./wordpress/wp-content/plugins:/var/www/html/wp-content/plugins/
    networks:
      - wp_private
      - wp_public
    labels:
      - "traefik.frontend.rule=Host:wordpress.docker.ianmonroe.com"
      - "traefik.port=80"
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=http,https"

  db:
    image: mysql:5
    container_name: wordpress-mysql
    restart: always
    ports:
      - "3306"
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./low-memory-my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_DATABASE=exampledb
      - MYSQL_USER=exampleuser
      - MYSQL_PASSWORD=examplepass
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_ROOT_PASSWORD=superdupersekret
    networks:
      - wp_private
    labels:
      - "traefik.enable=false"

  adminer:
    container_name: wordpress-adminer
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    ports:
      - "8080"
    networks:
      - wp_private
      - wp_public
    labels:
      - "traefik.backend=wordpress.adminer"
      - "traefik.frontend.passHostHeader:true"
      - "traefik.frontend.rule=Host:wordpress.docker.ianmonroe.com;PathPrefixStrip:/adminer"
      - "traefik.port=8080"
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=http,https"

networks:
  wp_public:
    external:
      name: frontend
  wp_private:
    driver: bridge
