version: '3.5'

services:

  wordpress:
    image: wordpress
    container_name: wordpress-webserver
    restart: always
    #ports:
    #  - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress/wp-content/themes:/var/www/html/wp-content/themes/
      - ./wordpress/wp-content/plugins:/var/www/html/wp-content/plugins/
    networks:
      - wp_private
      - wp_public
    labels:
      - "traefik.frontend.rule=Host:wordpress.docker.ianmonroe.com"
      - "traefik.port=80"
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=http,https"

  db:
    build:
      context: ../container_lomem_mysql
      dockerfile: Dockerfile
    # image: mysql:5
    container_name: wordpress-mysql
    restart: always
    ports:
      - "3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - wp_private
    labels:
      - "traefik.enable=false"

networks:
  wp_public:
    external:
      name: frontend
  wp_private:
    driver: bridge
