version: '3.5'

networks:
  monitor-net:
    driver: bridge
  stats_public:
    external:
      name: frontend

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  prometheus:
    image: prom/prometheus:v2.6.0
    container_name: stats_prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    #ports:
    #  - "9090"
    networks:
      - monitor-net
      - stats_public
    labels:
      - "org.label-schema.group=monitoring"
      - "traefik.backend=stats_prometheus"
      - "traefik.frontend.rule=Host:stats.docker.ianmonroe.com;PathPrefixStrip:/prometheus"
      - "traefik.port=9090"
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=http,https"

  alertmanager:
    image: prom/alertmanager:v0.15.3
    container_name: stats_alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    #ports:
    #  - "9093"
    networks:
      - monitor-net
      - stats_public
    labels:
      - "org.label-schema.group=monitoring"
      - "traefik.backend=stats_alertmanager"
      - "traefik.frontend.rule=Host:stats.docker.ianmonroe.com;PathPrefixStrip:/alertmanager"
      - "traefik.port=9093"
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=http,https"

  nodeexporter:
    image: prom/node-exporter:v0.17.0
    container_name: nodeexporter
    user: root
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    ports:
      - "9100"
    networks:
      - monitor-net
    labels:
      - "org.label-schema.group=monitoring"
      - "traefik.enable=false"

  cadvisor:
    image: google/cadvisor:v0.32.0
    container_name: stats_cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    restart: unless-stopped
    ports:
      - "8080"
    networks:
      - monitor-net
      - stats_public
    labels:
      - "org.label-schema.group=monitoring"
      - "traefik.backend=stats_cadvisor"
      - "traefik.frontend.rule=Host:stats.docker.ianmonroe.com;PathPrefixStrip:/cadvisor"
     - "traefik.port=8080"
     - "traefik.enable=true"
     - "traefik.frontend.entryPoints=http,https"

  grafana:
    image: grafana/grafana:5.4.2
    container_name: stats_grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/datasources
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/setup.sh:/setup.sh
    entrypoint: /setup.sh
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    #ports:
    #  - "3000"
    networks:
      - monitor-net
      - stats_public
    labels:
      - "org.label-schema.group=monitoring"
      - "traefik.backend=stats_grafana"
      - "traefik.frontend.rule=Host:stats.docker.ianmonroe.com"
      - "traefik.port=3000"
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=http,https"

  pushgateway:
    image: prom/pushgateway:v0.7.0
    container_name: stats_pushgateway
    restart: unless-stopped
    ports:
      - "9091"
    networks:
      - monitor-net
    labels:
      - "org.label-schema.group=monitoring"
      - "traefik.enable=false"

#  caddy:
#    image: stefanprodan/caddy
#    container_name: caddy
#    ports:
#      - "3000"
#      - "9090"
#      - "9093"
#      - "9091"
#    volumes:
#      - ./caddy/:/etc/caddy/
#    environment:
#      - ADMIN_USER=${ADMIN_USER:-admin}
#      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
#    restart: unless-stopped
#    networks:
#      - monitor-net
#      - stats_public
#    labels:
#      - "org.label-schema.group=monitoring"
#      - "traefik.backend=stats_app"
#      - "traefik.frontend.rule=Host:stats.docker.ianmonroe.com"
#      - "traefik.port=3000"
#      - "traefik.enable=true"
#      - "traefik.frontend.entryPoints=http,https"
