version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: application1-mysql
    volumes:
      - ./${STACK_NAME}/dbdata:/var/lib/mysql:rw
    user: mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306"

  webserver:
    build: config/nginx
    container_name: application1-webserver
    hostname: ${HOSTNAME}
    working_dir: /application
    volumes:
      - ./${STACK_NAME}/application:/application
      - ./${STACK_NAME}/config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - HOSTNAME=${HOSTNAME}
    #managed by Traefik
    #ports:
    #  - "${WEB_SERVER_PORT}:80"
    #  - "${WEB_SERVER_SSL_PORT}:443"
    labels:
      - "traefik.backend=app1"
      - "traefik.frontend.rule=PathPrefixStrip:/app1"
      - "traefik.port=80"
      - "traefik.enable=true"
      - "traefik.frontend.redirect.regex=^(.*)/app1$$"
      - "traefik.frontend.redirect.replacement=$$1/app1/"
      - "traefik.frontend.rule=PathPrefix:/app1;ReplacePathRegex: ^/app1/(.*) /$$1"

  php-fpm:
    build: config/php-fpm
    container_name: application1-php-fpm
    working_dir: /application
    volumes:
      - ./${STACK_NAME}/application:/application
      - ./${STACK_NAME}/config/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    environment:
      - HOSTNAME=${HOSTNAME}
