version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: application1-mysql
    volumes:
      - ./dbdata:/var/lib/mysql:rw
    user: mysql
    environment:
      - MYSQL_DATABASE=app1
      - MYSQL_USER=app1_user
      - MYSQL_PASSWORD=supersecretpassword
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306"

  webserver:
    build: ./config/nginx
    container_name: application1-webserver
    hostname: app1.localhost
    working_dir: /application
    volumes:
      - ./application:/application
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - HOSTNAME=app1.localhost
    #managed by Traefik
    #ports:
    #  - "${WEB_SERVER_PORT}:80"
    #  - "${WEB_SERVER_SSL_PORT}:443"
    labels:
      - "traefik.backend=app1"
      - "traefik.frontend.rule=PathPrefixStrip:/app1"
      - "traefik.port=80"
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=http,https"

  php-fpm:
    build: ./config/php-fpm
    container_name: application1-php-fpm
    working_dir: /application
    volumes:
      - ./application:/application
      - ./config/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    environment:
      - HOSTNAME=app1.localhost
