version: "3.5"
services:
  mysql:
    image: mysql:5
    container_name: application1-mysql
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=app1
      - MYSQL_USER=app1_user
      - MYSQL_PASSWORD=supersecretpassword
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=superdupersekret
    ports:
      - "3306"
    networks:
      - app1_private
    restart: always

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    ports:
      - "8080"
    networks:
      - app1_private
      - app1_public
    labels:
      - "traefik.backend=app1.adminer"
      - "traefik.frontend.rule=PathPrefixStrip:/app1/adminer"
      - "traefik.port=8080"
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=http,https"

  webserver:
    build: ./config/nginx
    container_name: application1-webserver
    hostname: app1.localhost
    working_dir: /application
    volumes:
      - ./application:/application
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - HOSTNAME=app1.localhost
    ports:
      - "80"
    labels:
      - "traefik.backend=app1"
      - "traefik.frontend.rule=PathPrefixStrip:/app1"
      - "traefik.port=80"
      - "traefik.enable=true"
      - "traefik.frontend.entryPoints=http,https"
    networks:
      - app1_private
      - app1_public

  php-fpm:
    build: ./config/php-fpm
    container_name: application1-php-fpm
    working_dir: /application
    volumes:
      - ./application:/application
      - ./config/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    environment:
      - HOSTNAME=app1.localhost
    networks:
      - app1_private

networks:
  app1_public:
    external:
      name: frontend
  app1_private:
    driver: bridge

