version: '3'
services:

  traefik:
    image: traefik:1.5.4
    restart: always
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
    container_name: traefik

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: --templates http://templates/templates.json
    labels:
      - "traefik.frontend.rule=Path:/portainer/"
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=PathPrefixStrip:/portainer"
      - "traefik.port=9000"
      - "traefik.enable=true"
    #managed by Traefik
    #ports:
    #  - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
      - ../shared_data:/shared
    environment:
      - TZ="America/Denver"

  watchtower:
    container_name: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup

